name: Syncher

on:
  schedule:
    - cron: 0 12 * * *

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: |
          go install github.com/lildude/oura-to-runalyze@latest
          oura-to-runalyze -yesterday
        env:
          OURA_ACCESS_TOKEN: ${{ secrets.OURA_ACCESS_TOKEN }}
          RUNALYZE_ACCESS_TOKEN: ${{ secrets.RUNALYZE_ACCESS_TOKEN }}